### ISSUE TITLE
Integrate Azure Pipelines

### ISSUE THREAD

**Issue by MaximRouiller** [MaximRouiller/vscode-social-linker#13]
We need start building those apps and having feedbacks directly.

**Comment by salmanmkc** [comment]
was confused when I saw this issue, but then realised you self-assigned it :)

**Comment by MaximRouiller** [comment]
Yeah, it's mostly already done. 

We're starting with a simple build to have all the errors/warning pop up.  As we move forward, I'll integrate the CD part of CI/CD. Maybe even add tests if people are willing to write some.

**Comment by salmanmkc** [comment]
yeah sure, don't mind looking into writing some tests down the line
